version: "3.8"

services:
  mysqldb:
    image: mysql:5.7
    restart: unless-stopped
    env_file: ./.env
    environment:
      - MYSQL_ROOT_PASSWORD=$MYSQLDB_ROOT_PASSWORD
      - MYSQL_DATABASE=$MYSQLDB_DATABASE
    ports:
#      - $MYSQLDB_LOCAL_PORT:$MYSQLDB_DOCKER_PORT
      - "3307:3306"
  discovery-server:
    image: discovery-server:1.0-SNAPSHOT
    restart: on-failure
    ports:
      #      - $SERVER_SPRING_LOCAL_PORT:$SERVER_SPRING_DOCKER_PORT
      - "8761:8761"
    environment:
      SPRING_APPLICATION_JSON: '{
              "eureka.client.service-url.defaultZone" : "http://discovery-server:8761/eureka",
              "eureka.client.register-with-eureka" : false,
              "eureka.client.fetch-registry": false,
              "eureka.instance.prefer-ip-address" : true
            }'
  api-gateway:
    depends_on:
      - discovery-server
    image: api-gateway:1.0-SNAPSHOT
    restart: on-failure
    ports:
      #      - $GATEWAY_SPRING_LOCAL_PORT:$GATEWAY_SPRING_DOCKER_PORT
      - "8082:8082"
    environment:
      SPRING_APPLICATION_JSON: '{
              "spring.application.name":"api-gateway",
              "eureka.client.service-url.defaultZone":"http://discovery-server:8761/eureka",
              "spring.cloud.gateway.discovery.locator.enabled":true,
              "spring.cloud.gateway.discovery.locator.lower-case-service-id":true
          }'
  blog-post-service:
    depends_on:
      - mysqldb
      - discovery-server
    image: blog-service:1.0-SNAPSHOT 
    restart: on-failure
    env_file: ./.env
    ports:
#      - $BLOG_SPRING_LOCAL_PORT:$BLOG_SPRING_DOCKER_PORT
      - "8083:8083"
    environment:
      SPRING_APPLICATION_JSON: '{
        "spring.datasource.url"  : "jdbc:mysql://mysqldb:3306/$MYSQLDB_DATABASE?useSSL=false&serverTimezone=America/Chicago&allowPublicKeyRetrieval=true",
        "spring.datasource.username" : "$MYSQLDB_USER",
        "spring.datasource.password" : "$MYSQLDB_ROOT_PASSWORD",
        "spring.jpa.properties.hibernate.dialect" : "org.hibernate.dialect.MySQL5Dialect",
        "spring.jpa.hibernate.ddl-auto" : "create-drop",
        "spring.jpa.show-sql":true,
        "spring.jpa.properties.hibernate.format_sql":true,
        "spring.application.name":"blog-post-service",
        "eureka.client.service-url.defaultZone":"http://discovery-server:8761/eureka"
      }'
  blog-comment-service:
    depends_on:
      - mysqldb
      - discovery-server
    image: blog-comment-service:1.0-SNAPSHOT
    restart: on-failure
    env_file: ./.env
    ports:
#      - $COMMENT_SPRING_LOCAL_PORT:$COMMENT_SPRING_DOCKER_PORT
      - "8081:8081"
    environment:
      SPRING_APPLICATION_JSON: '{
          "spring.datasource.url"  : "jdbc:mysql://mysqldb:3306/$MYSQLDB_DATABASE?useSSL=false&serverTimezone=America/Chicago&allowPublicKeyRetrieval=true",
          "spring.datasource.username" : "$MYSQLDB_USER",
          "spring.datasource.password" : "$MYSQLDB_ROOT_PASSWORD",
          "spring.jpa.properties.hibernate.dialect" : "org.hibernate.dialect.MySQL5Dialect",
          "spring.jpa.hibernate.ddl-auto" : "create-drop",
          "spring.jpa.show-sql":true,
          "spring.jpa.properties.hibernate.format_sql":true,
          "spring.application.name" : "blog-comment-service",
          "eureka.client.service-url.defaultZone":"http://discovery-server:8761/eureka"
        }'
  authentication-authorization-service:
    depends_on:
      - mysqldb
      - discovery-server
    image: authentication-authorization-service:1.0-SNAPSHOT
    restart: on-failure
    env_file: ./.env
    ports:
#      - $AUTH_SPRING_LOCAL_PORT:$AUTH_SPRING_DOCKER_PORT
      - "8080:8080"
    environment:
      SPRING_APPLICATION_JSON: '{
          "spring.datasource.url"  : "jdbc:mysql://mysqldb:3306/$MYSQLDB_DATABASE?useSSL=false&serverTimezone=America/Chicago&allowPublicKeyRetrieval=true",
          "spring.datasource.username" : "$MYSQLDB_USER",
          "spring.datasource.password" : "$MYSQLDB_ROOT_PASSWORD",
          "spring.jpa.properties.hibernate.dialect" : "org.hibernate.dialect.MySQL5Dialect",
          "spring.jpa.hibernate.ddl-auto" : "create-drop",
          "spring.jpa.show-sql":true,
          "spring.jpa.properties.hibernate.format_sql":true,
          "spring.application.name":"authentication-authorization-service",
          "eureka.client.service-url.defaultZone":"http://discovery-server:8761/eureka"
        }'

